export const WORK = [
  {
    t: "Coaching",
    h: "Transform the whole person",
    v: "light",
    cap: "Training floor",
    src: "/assets/img/room-coaching.png",
    href: "/coaching",
    cta: "Explore coaching",
    d: "You cannot fix the spirit and ignore the body, and you cannot fix the body and ignore what is going on in your head. Garth is a Westside Barbell-certified trainer, a nutritionist, a business coach and a pastor. The plan gets built from all four at once.",
    tags: ["Nutrition", "Personal training", "Emotional", "Mental", "Social", "Spiritual"],
  },
  {
    t: "Speaking",
    h: "You would love having Garth at your next event",
    v: "warm",
    cap: "On stage, house lights down",
    src: "/assets/img/room-speaking.png",
    href: "/speaking",
    cta: "Check availability",
    d: "Hundreds of thousands of students and leaders, on stages from Wisconsin to the other side of the world. He earns the room in the first ninety seconds and does not waste the rest of it.",
    tags: ["Conferences", "Sunday services", "Staff days", "Student events", "Men's events"],
  },
  {
    t: "Cancer",
    h: "Triple C survivor",
    v: "light",
    cap: "Warm, honest, not heroic",
    src: "/assets/img/room-cancer.png",
    href: "/cancer",
    cta: "If you are in the fight",
    d: "Three cancers, a brain tumor, an enlarged heart. Garth has been on the table, in the chair and through the scans, and he knows exactly what the two-week wait for results does to a person. He is not going to hand you a verse and walk off.",
    tags: ["Hope", "Resources", "A straight conversation"],
  },
  {
    t: "Simply Church",
    h: "A thousand living rooms",
    v: "cool",
    cap: "Ten people, coffee, no stage",
    src: "/assets/img/room-church.png",
    href: "/simply-church",
    cta: "Start one in your living room",
    d: "Not a thousand campuses, but a thousand rooms where people actually know each other’s names and each other’s worst week. Much like the first church in Acts 2, and considerably less complicated than what came after it.",
    tags: ["Acts 2", "House gatherings", "No building", "Start your own"],
  },
  {
    t: "Relationship Recall",
    h: "I'm going to try to break up your relationship",
    v: "warm",
    cap: "Two chairs, one hard conversation",
    src: "/assets/img/room-relationship.png",
    href: "/relationship-recall",
    cta: "Get the first email",
    d: "Every week. It’s true. Most coaches encourage and equip. To Garth that is painting a burning house. He goes looking for the thing that will actually end it, puts it on the table, and then helps you rebuild the foundation underneath.",
    tags: ["One email a week", "Find the cracks", "Rebuild", "Total recall"],
  },
  {
    t: "Bridgeworks",
    h: "Understand. Attract. Connect. Disciple.",
    v: "cool",
    cap: "Staff room, five ages, one table",
    src: "/assets/img/room-bridgeworks.png",
    href: "/bridgeworks",
    cta: "Book a discovery call",
    d: "Ask Garth to teach your business, church or church staff how to Understand, Attract, Connect and Disciple. He works with the senior pastor, the staff and the congregation together, and leaves a written plan of attack rather than a workshop hangover.",
    tags: ["Retention", "Connection", "Culture", "Communication"],
  },
] as const;

export const YOUTUBE_CHANNEL = "https://www.youtube.com/@garthheckman9650";

export const YOUTUBE_SHORTS = [
  {
    id: "bZJ5YaOe8yw",
    t: "You DO NOT have what it takes!",
    v: "warm",
  },
  {
    id: "zLC4urADyP4",
    t: "Be the Investigative Reporter",
    v: "default",
  },
  {
    id: "c843k3KgeVE",
    t: "ReFrame for Protection",
    v: "cool",
  },
] as const;

export const FORGE_ROWS = [
  {
    age: "Age 17",
    tag: "1970s",
    t: "A broken neck, in three places",
    d: "Six months in a halo vest. Multiple surgeries, and physical therapy while paralysis threatened his arms.",
    yet: "He walked out of it.",
  },
  {
    age: "Three",
    tag: "",
    t: "Cancer, three separate times",
    d: "Triple C survivor. He calls his own journey spectacularly miraculous, and he will tell you the whole thing if you ask.",
    yet: "All three, survived.",
  },
  {
    age: "One",
    tag: "",
    t: "A brain tumor",
    d: "One of several diagnoses that, on paper, should have claimed his life well before now.",
    yet: "Still preaching.",
  },
  {
    age: "Since",
    tag: "Ongoing",
    t: "An enlarged heart",
    d: "A Westside Barbell-certified trainer who has spent decades in gyms, carrying a heart that keeps trying to quit.",
    yet: "Still in the gym.",
  },
] as const;

export { BLOG_POSTS } from "@/lib/blog";

export const BLOG_HREF = "/blog";

export const EPISODES = [
  {
    no: "1736",
    dur: "48:12",
    date: "09 Aug 26",
    tag: "leadership",
    feat: true,
    v: "warm",
    t: "Five generations, one room, and everybody heard a different sermon",
    d: "Traditionalists built it, Boomers led it, Gen X is running it, Millennials want it to be real, and Gen Z will show up for honesty and nothing else.",
  },
  {
    no: "1735",
    dur: "31:04",
    date: "02 Aug 26",
    tag: "resilience",
    t: "What three cancers actually taught me",
    d: "Not the version people expect, and not the one that fits on a poster.",
  },
  {
    no: "1734",
    dur: "26:47",
    date: "26 Jul 26",
    tag: "relationships",
    t: "Painting a burning house",
    d: "Why most relationship advice fails, and what is cracking underneath.",
  },
  {
    no: "1733",
    dur: "39:20",
    date: "19 Jul 26",
    tag: "resilience",
    t: "Six months in a halo vest at seventeen",
    d: "Broken neck in three places. What that does to a kid who thought he was invincible.",
  },
  {
    no: "1732",
    dur: "22:58",
    date: "12 Jul 26",
    tag: "faith",
    t: "Nobody is coming to fix your fitness",
    d: "On restarting the same plan four times a year and calling it discipline.",
  },
  {
    no: "1731",
    dur: "27:41",
    date: "05 Jul 26",
    tag: "leadership",
    t: "The question nobody in the room will ask",
    d: "Forty years of coaching pastors, distilled into one uncomfortable sentence.",
  },
  {
    no: "1730",
    dur: "35:12",
    date: "28 Jun 26",
    tag: "faith",
    t: "A church with a reputation for being alive",
    d: "Revelation 3, and why it still lands harder than anything else he preaches.",
  },
  {
    no: "1729",
    dur: "19:33",
    date: "21 Jun 26",
    tag: "relationships",
    t: "The thing you have agreed not to mention",
    d: "One question, asked properly, changes more than a year of advice.",
  },
  {
    no: "1728",
    dur: "41:07",
    date: "14 Jun 26",
    tag: "leadership",
    t: "Handing it over without letting it drop",
    d: "Succession in a church that three generations built.",
  },
  {
    no: "1727",
    dur: "24:19",
    date: "07 Jun 26",
    tag: "faith",
    t: "Make God look good",
    d: "The four-word mission, and where it came from.",
  },
] as const;

export const SEARCH_PAGES = [
  {
    t: "The David Alliance",
    d: "The podcast. Short, unsentimental episodes on faith, leadership and getting back up.",
    href: "/podcast",
    tags: "podcast episodes listen audio",
  },
  {
    t: "What I Do",
    d: "Six areas of work: coaching, speaking, cancer, church, marriage and generations.",
    href: "/work",
    tags: "services areas work",
  },
  {
    t: "My Story",
    d: "Forty-two years in ministry. Three cancers, a brain tumor and a broken neck.",
    href: "/story",
    tags: "bio about biography forged by fire",
  },
  {
    t: "Speaking",
    d: "Bring Garth to your next event. Conferences, churches, staff days and student nights.",
    href: "/speaking",
    tags: "book booking event keynote hire",
  },
  {
    t: "Store",
    d: "Books, downloads and merchandise.",
    href: "/store",
    tags: "shop buy products merch",
  },
  {
    t: "Blog",
    d: "Writing on marriage and relationships, generational differences, and evangelism.",
    href: "/blog",
    tags: "journal articles writing",
  },
  {
    t: "Connect",
    d: "Speaking inquiries, coaching, Simply Church, Bridgeworks, or just to say hello.",
    href: "/contact",
    tags: "contact email get in touch inquiry",
  },
  {
    t: "Coaching",
    d: "Nutrition, wellness, certified personal training and the mental side of change.",
    href: "/coaching",
    tags: "health fitness training nutrition mentor",
  },
  {
    t: "Simply Church",
    d: "A thousand churches gathering in living rooms across the country. Acts 2.",
    href: "/simply-church",
    tags: "house church home group acts 2",
  },
  {
    t: "Cancer",
    d: "Triple C survivor. Hope, resources and a straight conversation.",
    href: "/cancer",
    tags: "diagnosis survivor illness treatment hope",
  },
  {
    t: "Relationship Recall",
    d: "Finds the cracks in the foundation, exposes them and rebuilds. One email a week.",
    href: "/relationship-recall",
    tags: "marriage couples relationship counseling",
  },
  {
    t: "Bridgeworks",
    d: "Generational intelligence for churches and businesses. Understand, Attract, Connect and Disciple.",
    href: "/bridgeworks",
    tags: "generations boomers gen x millennials gen z",
  },
  {
    t: "Orders & downloads",
    d: "Look up an order by email and get your files.",
    href: "/account",
    tags: "account order lookup downloads receipt",
  },
    {
    t: "Cart",
    d: "Review what you are buying.",
    href: "/cart",
    tags: "basket checkout",
  },
  {
    t: "Sitemap",
    d: "Every public page on this site, in one list.",
    href: "/sitemap",
    tags: "map pages index",
  },
  {
    t: "Service Index",
    d: "Coaching, speaking, cancer, church, marriage, generations. Six rooms and the rest.",
    href: "/service-index",
    tags: "services directory work",
  },
  {
    t: "AI Policy",
    d: "How this site uses artificial intelligence, and what it does not do with it.",
    href: "/ai-policy",
    tags: "artificial intelligence machines",
  },
  {
    t: "Privacy Policy",
    d: "What this site collects, why, and how to ask for it back.",
    href: "/privacy",
    tags: "privacy data cookies paypal",
  },
] as const;

export const SEARCH_TRENDING = [
  { t: "Wake The Faith Up", href: "/product/wtfu-book" },
  { t: "Book Garth to speak", href: "/speaking" },
  { t: "Latest episode", href: "/podcast" },
  { t: "My story", href: "/story" },
  { t: "Coaching", href: "/coaching" },
  { t: "If you are in the fight", href: "/cancer" },
  { t: "Store", href: "/store" },
] as const;
